name: CI
on: push

env:
  GITOPS_PROJECT_NAME: gitops
  PROJECT_NAME: book
  DOCKER_NAME: mizotakhteh.book

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --verbose
      - run: cargo test --verbose

  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install musl-tools
      - run: rustup update nightly && rustup default nightly
      - run: rustup target add x86_64-unknown-linux-musl
      - run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Upload binary result
        uses: actions/upload-artifact@v4
        with:
          name: binary_result
          path: target/x86_64-unknown-linux-musl/release/${{ env.PROJECT_NAME }}
          retention-days: 1

  package:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
      - name: Download binary result
        uses: actions/download-artifact@v4
        with:
          name: binary_result
          path: target/x86_64-unknown-linux-musl/release/
      - run: chmod +x target/x86_64-unknown-linux-musl/release/${{ env.PROJECT_NAME }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_NAME }}"
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - package
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ env.GITOPS_PROJECTNAME }}"
          token: ${{ secrets.GIT_TOKEN }}
      - run: |
          sed -i "s/(image:.*\n.*- name: ${{ github.repository_owner }}\/${{ env.DOCKER_NAME }}.*\n.*newTag: ).*/${{ github.ref_name }}/g" \
            ${{ env.PROJECT_NAME }}/overlay/dev/Kustomization.yaml
      - run: |
          git config --global user.name "Hasan Karimi"
          git config --global user.email "hasankarimi.dev@gmail.com"
          git add .
          git commit -m "ci(${{ env.PROJECT_NAME }}): update image with tag=(${{ github.ref_name }} )"
          git push origin
