name: Main
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --verbose
      - run: cargo test --verbose

  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup default nightly
      - run: cargo build --release --target x86_64-unknown-linux-musl

  package:
    runs-on: ubuntu-latest
    needs:
      - release-build
    steps:
      - uses: actions/checkout@v4

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - package
    steps:
      - uses: actions/checkout@v4
